Repository canonical/cs.canonical.com, pull requests merged in 2024-08, with the labels that each got.

#30 Added python CI
  .env
  .github/workflows/CI.yml
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  konf/site.yaml
  pyproject.toml
  requirements.txt
  static/client/config/index.ts
  webapp/app.py
  webapp/cache.py
  webapp/parse_tree.py
  webapp/parser_task.py
  webapp/settings.py
  webapp/site_repository.py
  webapp/tasks.py
Labels: Review: QA +1, Review: Code +1

#32 [WD-13865] redesign UI
  static/client/App.scss
  static/client/_settings.scss
  static/client/components/Breadcrumbs/Breadcrumbs.tsx
  static/client/components/Breadcrumbs/Breadcrumbs.types.ts
  static/client/components/Breadcrumbs/index.ts
  static/client/components/MainLayout/MainLayout.tsx
  static/client/components/MainLayout/_MainLayout.scss
  static/client/components/Navigation/Navigation.tsx
  static/client/components/Navigation/NavigationBanner/NavigationBanner.tsx
  static/client/components/Navigation/NavigationElement/NavigationElement.tsx
  static/client/components/Navigation/NavigationItems/NavigationItems.tsx
  static/client/components/Navigation/_Navigation.scss
  static/client/components/Search/Search.services.ts
  static/client/components/Search/Search.tsx
  static/client/components/SiteSelector/SiteSelector.tsx
  static/client/components/SiteSelector/index.ts
  static/client/config/index.ts
  static/client/pages/Webpage/Webpage.tsx
  static/client/pages/Webpage/_Webpage.scss
  static/client/store/index.ts
  static/client/store/types.ts
  webapp/app.py
Labels: Review: QA +1, Code +1 with changes

#35 Create cronjobs
  .env
  README.md
  migrations/env.py
  migrations/versions/28a719de7ec9_.py
  migrations/versions/ce63548f31e6_.py
  webapp/app.py
  webapp/context.py
  webapp/models.py
  webapp/settings.py
  webapp/site_repository.py
  webapp/tasks.py
Labels: Review: QA +1, Review: Code +1

#36 [WD-13297] add get-users route that fetches users from directory-api
  .env
  requirements.txt
  webapp/app.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#40 Add set reviewers endpoint
  webapp/app.py
  webapp/helper.py
Labels: Review: QA +1, Review: Code +1
