Repository canonical/cs.canonical.com, pull requests merged in 2025-05, with the labels that each got.

#189 Bugfix: Updated url for directory API
  webapp/helper.py
Labels: Review: QA Needed, Review: Code +1

#184 Feat: Project Views in content system
  README.md
  static/client/App.scss
  static/client/components/Breadcrumbs/Breadcrumbs.tsx
  static/client/components/Common/IconTextWithTooltip.tsx
  static/client/components/MainLayout/MainLayout.tsx
  static/client/components/Navigation/Navigation.tsx
  static/client/components/Navigation/NavigationElement/NavigationElement.types.ts
  static/client/components/Navigation/NavigationElement/NavigationElementBadge.tsx
  static/client/components/Navigation/_Navigation.scss
  static/client/components/OwnerAndReviewers/Owner.tsx
  static/client/components/OwnerAndReviewers/OwnerAndReviewers.types.ts
  static/client/components/OwnerAndReviewers/Reviewers.tsx
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
  static/client/components/SiteSelector/SiteSelector.tsx
  static/client/components/Views/FilterTableView/FilterTableView.tsx
  static/client/components/Views/FilterTableView/FilterandSearch.tsx
  static/client/components/Views/FilterTableView/SearchProductCheckbox.tsx
  static/client/components/Views/FilterTableView/SearchUserCheckbox.tsx
  static/client/components/Views/FilterTableView/_FilterTableView.scss
  static/client/components/Views/FilterTableView/index.ts
  static/client/components/Views/TableView/Products.tsx
  static/client/components/Views/TableView/ProjectContent.tsx
  static/client/components/Views/TableView/ProjectTitle.tsx
  static/client/components/Views/TableView/Reviewers.tsx
  static/client/components/Views/TableView/TableView.tsx
  static/client/components/Views/TableView/TableViewRow.tsx
  static/client/components/Views/TableView/TableViewRowItem.tsx
  static/client/components/Views/TableView/index.ts
  static/client/config/index.ts
  static/client/helpers/views.ts
  static/client/pages/Main/Main.tsx
  static/client/pages/NewWebpage/NewWebpage.tsx
  static/client/pages/Webpage/Webpage.tsx
  static/client/pages/views/Owned.tsx
  static/client/pages/views/Reviewed.tsx
  static/client/services/api/hooks/projects.ts
  static/client/services/api/hooks/users.ts
  static/client/services/api/types/pages.ts
  static/client/services/api/types/views.ts
  static/client/store/types.ts
  static/client/store/views.ts
  webapp/app.py
  webapp/helper.py
  webapp/routes/user.py
Labels: Review: QA +1

#188 [WD-21847] fix: sort the newly generated tree struct
  webapp/site_repository.py
Labels: Review: QA +1, Review: Code +1

#190 [WD-21921] chore: clean up HMR config
  README.md
  vite.config.ts
Labels: Review: QA +1, Review: Code +1

#191 [WD-21922] chore: clean up nested routes
  static/client/pages/Main/Main.tsx
  static/client/pages/NewWebpage/NewWebpage.tsx
  static/client/services/routes/index.tsx
Labels: Review: QA +1, Review: Code +1

#192 fix: dark icon
  static/client/components/Navigation/NavigationElement/NavigationElement.tsx
  static/client/components/Views/FilterTableView/FilterandSearch.tsx
  static/client/components/Views/FilterTableView/_FilterTableView.scss
Labels: Review: QA +1, Review: Code +1

#182 Fix bg tasks
  .dockerignore
  .github/workflows/CI.yml
  Dockerfile
  README.md
  app.py
  entrypoint
  webapp/__init__.py
  webapp/app.py
  webapp/cache.py
  webapp/celery.py
  webapp/context.py
  webapp/github.py
  webapp/models.py
  webapp/scheduled_tasks.py
  webapp/site_repository.py
  webapp/tasklib.py
  webapp/tasks.py
Labels: Review: Code Needed, Review: QA -1

#197 [WD-22036] feat: attach Jira task with webpage, provided copydoc link
  webapp/routes/jira.py
  webapp/schemas.py
Labels: Review: QA +1, Review: Code +1
