Repository canonical/cs.canonical.com, pull requests merged in 2025-01, with the labels that each got.

#102 WD-17982 Fix console errors
  static/client/components/Navigation/NavigationItems/NavigationItems.tsx
  static/client/components/OwnerAndReviewers/CustomSearchAndFilter.tsx
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
Labels: Review: Code +1

#103 feat: Update reviewers and owners for a page in real-time, without having to reload (WD-17983)
  static/client/components/OwnerAndReviewers/Owner.tsx
  static/client/components/OwnerAndReviewers/Reviewers.tsx
Labels: Review: QA +1, Review: Code +1

#95 Moved dashboard to /app endpoint
  static/client/components/Breadcrumbs/Breadcrumbs.tsx
  static/client/components/MainLayout/MainLayout.test.tsx
  static/client/components/MainLayout/MainLayout.tsx
  static/client/components/Navigation/Navigation.tsx
  static/client/components/Navigation/NavigationItems/NavigationItems.tsx
  static/client/components/Search/Search.tsx
  static/client/components/SiteSelector/SiteSelector.tsx
  static/client/main.test.tsx
  static/client/pages/Main/Main.tsx
  static/client/services/routes/index.tsx
  templates/login.html
  webapp/__init__.py
  webapp/app.py
  webapp/sso.py
Labels: Review: QA Needed, Review: Code Needed

#101 WD-16245 Add tooltips to request types when creating a Jira request
  static/client/App.scss
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
Labels: Review: QA +1, Review: Code +1

#106 Backend functionality for getting current logged in user's information from canonical directory, and storing it in users table upon login
  webapp/helper.py
  webapp/routes/user.py
  webapp/sso.py
Labels: Review: QA +1, Review: Code +1

#105 [WD-16242] Backend functionality for setting products on webpages
  konf/data.yaml
  migrations/versions/636e244e00ea_.py
  webapp/app.py
  webapp/helper.py
  webapp/models.py
  webapp/routes/product.py
  webapp/schemas.py
Labels: Review: QA +1, Review: Code +1

#107 [WD-18147] Persist currently logged in user's info on the frontend and show in sidebar
  static/client/App.tsx
  static/client/components/Navigation/Navigation.tsx
  static/client/components/Navigation/_Navigation.scss
  static/client/pages/Main/Main.tsx
  static/client/services/api/constants.ts
  static/client/services/api/hooks/auth.ts
  static/client/services/api/partials/UsersApiClass.ts
  static/client/services/api/services/users.ts
  static/client/store/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#109 [WD-18202] fix: invalid prefix in breadcrumbs and links not working
  static/client/components/Breadcrumbs/Breadcrumbs.tsx
Labels: Review: QA +1, Review: Code +1

#108 [WD-16244] Select current user as a reporter for jira task when requesting page changes or removal
  .env
  static/client/components/Navigation/Navigation.tsx
  static/client/components/OwnerAndReviewers/OwnerAndReviewers.types.ts
  static/client/components/OwnerAndReviewers/Reporter.tsx
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
  static/client/pages/NewWebpage/NewWebpage.tsx
  static/client/services/api/constants.ts
  static/client/services/api/types/pages.ts
  static/client/store/index.ts
  static/client/store/types.ts
  webapp/helper.py
  webapp/routes/jira.py
  webapp/schemas.py
Labels: Review: QA +1, Review: Code +1

#111 [WD-16243] Render, associate and update products with webpages
  static/client/components/Common/CustomSearchAndFilter.tsx
  static/client/components/OwnerAndReviewers/Owner.tsx
  static/client/components/OwnerAndReviewers/OwnerAndReviewers.types.ts
  static/client/components/OwnerAndReviewers/Reviewers.tsx
  static/client/components/Products/Products.tsx
  static/client/components/Products/Products.types.ts
  static/client/components/Products/index.ts
  static/client/components/Reporter/Reporter.tsx
  static/client/components/Reporter/Reporter.types.ts
  static/client/components/Reporter/index.ts
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
  static/client/pages/NewWebpage/NewWebpage.tsx
  static/client/pages/Webpage/Webpage.tsx
  static/client/services/api/constants.ts
  static/client/services/api/hooks/products.ts
  static/client/services/api/index.ts
  static/client/services/api/partials/PagesApiClass.ts
  static/client/services/api/partials/ProductsApiClass.ts
  static/client/services/api/services/pages.ts
  static/client/services/api/services/products.ts
  static/client/services/api/types/pages.ts
  static/client/services/api/types/products.ts
  static/client/services/api/types/query.ts
  webapp/routes/jira.py
  webapp/schemas.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#110 [WD-18271] fix: current date returns an assertion error when requesting page removal
  webapp/schemas.py
Labels: Review: QA Needed, Review: Code Needed

#116 [WD-18356] Update definitions for Copy update and Page refreshes
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
Labels: Review: QA +1, Review: Code +1

#115 [WD-18341] List steps to update env on prod pods
  README.md
Labels: Review: Code +1

#118 [WD-16233] update Jira task statuses
  .env
  .github/workflows/playwright.yml
  webapp/helper.py
  webapp/jira.py
  webapp/models.py
  webapp/tasks.py
Labels: Review: QA +1, Review: Code +1

#124 [WD-18864] Fixed selected page not highlighted in sidebar
  static/client/components/Navigation/NavigationItems/NavigationItems.tsx
Labels: Review: QA +1, Review: Code +1
