Repository canonical/cs.canonical.com, pull requests merged in 2025-02, with the labels that each got.

#127 use ds25 provided TS configuration and extend from it
  auto-imports.d.ts
  package.json
  static/client/main.test.tsx
  tsconfig.json
  yarn.lock
Labels: Review: QA Needed, Review: Code Needed

#132 [WD-18893] Scroll to selected webpage in side nav
  static/client/components/Navigation/NavigationElement/NavigationElement.tsx
Labels: Review: QA +1, Review: Code +1

#157 [WD-19149] Fixed redirection on removing a NEW webpage
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
Labels: Review: Code +1

#158 feat: Use canonical launchpad group on prod
  konf/site.yaml
  webapp/sso.py
Labels: Review: QA +1, Review: Code +1

#156 [WD-16291] Add redirect_url + Clear cache on NEW page removal and update side navigation
  static/client/components/JiraTasks/JiraTasks.tsx
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
  static/client/services/api/types/pages.ts
  webapp/routes/jira.py
  webapp/schemas.py
Labels: Review: QA +1, Review: Code +1
