Repository canonical/cs.canonical.com, pull requests merged in 2025-08, with the labels that each got.

#212 clone the whole repository instead of calling API for each repo file
  .gitignore
  Dockerfile
  entrypoint
  requirements.txt
  static/client/components/SiteSelector/SiteSelector.tsx
  webapp/github.py
  webapp/routes/jira.py
  webapp/scheduled_tasks.py
  webapp/schemas.py
  webapp/site_repository.py
  webapp/tests/test_gdrive.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#203 [WD-22490] chore: update playwright tests
  README.md
  static/client/components/OwnerAndReviewers/Owner.tsx
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
  static/client/config/index.ts
  static/client/global.d.ts
  static/client/services/api/hooks/pages.ts
  tests/config.ts
  tests/index.spec.ts
  tests/project.spec.ts
  tests/utils/common.ts
  tests/views/table-view.spec.ts
Labels: Review: QA +1, Review: Code +1

#217 [WD-23891] add more projects
  README.md
  data/sites.yaml
  entrypoint
  static/client/config/index.ts
  static/client/services/api/constants.ts
  webapp/context.py
  webapp/github.py
  webapp/parse_tree.py
  webapp/routes/tree.py
  webapp/scheduled_tasks.py
  webapp/site_repository.py
Labels: Review: QA +1, Review: Code +1

#216 [WD-21379] feat: Parse web page assets in a background task, and add an API endpoint to fetch assets for a specific webpage
  .env
  migrations/versions/1b6109065dba_.py
  webapp/app.py
  webapp/github.py
  webapp/models.py
  webapp/parse_tree.py
  webapp/routes/webpage.py
  webapp/scheduled_tasks.py
  webapp/schemas.py
  webapp/settings.py
  webapp/site_repository.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#222 feat: Refresh or deploy charm
  .github/workflows/deploy.yaml
Labels: Review: Code +1

#223 Fix deployment script bug
  .github/workflows/deploy.yaml
Labels: Review: Code +1

#224 [WD-23824] upgrade Vanilla version and convert to use new 8-column grid
  package.json
  static/client/App.scss
  static/client/components/Common/CustomSearchAndFilter.tsx
  static/client/components/JiraTasks/JiraTasks.tsx
  static/client/components/MainLayout/MainLayout.tsx
  static/client/components/Navigation/Navigation.test.tsx
  static/client/components/Navigation/Navigation.tsx
  static/client/components/Navigation/NavigationBanner/NavigationBanner.tsx
  static/client/components/Navigation/NavigationCollapseToggle/NavigationCollapseToggle.tsx
  static/client/components/Navigation/NavigationElement/NavigationElement.tsx
  static/client/components/Navigation/NavigationElement/NavigationElementBadge.tsx
  static/client/components/OwnerAndReviewers/Owner.tsx
  static/client/components/OwnerAndReviewers/OwnerAndReviewers.tsx
  static/client/components/OwnerAndReviewers/OwnerAndReviewers.types.ts
  static/client/components/OwnerAndReviewers/Reviewers.tsx
  static/client/components/Products/Products.tsx
  static/client/components/Reporter/Reporter.tsx
  static/client/components/RequestTaskModal/RequestTaskModal.tsx
  static/client/components/Search/Search.tsx
  static/client/components/SiteSelector/SiteSelector.tsx
  static/client/components/Views/FilterTableView/FilterTableView.tsx
  static/client/components/Views/FilterTableView/FilterandSearch.tsx
  static/client/components/Views/FilterTableView/SearchProductCheckbox.tsx
  static/client/components/Views/FilterTableView/SearchUserCheckbox.tsx
  static/client/components/Views/FilterTableView/_FilterTableView.scss
  static/client/pages/NewWebpage/NewWebpage.tsx
  static/client/pages/Webpage/Webpage.tsx
  static/client/services/routes/index.tsx
  templates/login.html
  tests/project.spec.ts
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#227 feat: stage git binary
  rockcraft.yaml
Labels: Review: Code +1

#225 [WD-24286] feat: Render paginated assets on a web page
  static/client/App.scss
  static/client/components/Views/TableView/ProjectTitle.tsx
  static/client/components/WebpageAssets/Asset.tsx
  static/client/components/WebpageAssets/index.tsx
  static/client/config/index.ts
  static/client/pages/Webpage/Webpage.tsx
  static/client/services/api/constants.ts
  static/client/services/api/hooks/assets.ts
  static/client/services/api/partials/PagesApiClass.ts
  static/client/services/api/services/pages.ts
  static/client/services/api/types/assets.ts
  webapp/routes/webpage.py
  webapp/scheduled_tasks.py
Labels: enhancement, Review: QA +1, Review: Code +1, UX + 1
